# -*- coding: utf-8 -*-
"""Предсказание прибыли с помощью линейной регрессии.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K5Os-132QUg7AFgLZxAj7zYKDGb6BvWB

Предсказание прибыли с помощью линейной регрессии
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Startups.csv")
print(data.head())
print('\n')
print(data.describe())
print('\n')
sns.heatmap(data.corr(), annot=True)
plt.show()
x = data[["R&D Spend", "Administration", "Marketing Spend"]]
y = data["Profit"]

x = x.to_numpy()
y = y.to_numpy()
y = y.reshape(-1, 1)

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(xtrain, ytrain)
ypred = model.predict(xtest)
data = pd.DataFrame(data={"Predicted Profit": ypred.flatten()})
print(data.head())